---
os: linux

dist: bionic

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
  - mysql
  - postgresql

language: ruby

rvm:
  - 2.3.8
  - 2.4.4
  - 2.5.1

env:
  - DB=mysql
  - DB=postgres

gemfile:
  - gemfiles/spree_3_5.gemfile
  - gemfiles/spree_3_7.gemfile
  - gemfiles/spree_4_0.gemfile
  - gemfiles/spree_master.gemfile

jobs:
  exclude:
    - rvm: 2.5.1
      gemfile: gemfiles/spree_3_5.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/spree_4_0.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/spree_4_0.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/spree_master.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/spree_master.gemfile
  allow_failures:
    - gemfile: gemfiles/spree_master.gemfile

before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

script:
  - bundle exec rake -t
